# ================================================================
#  MedFlow - Configuracao
# ================================================================
supabase.url=aws-1-us-east-2.pooler.supabase.com
supabase.port=5432
supabase.db=postgres
supabase.username=postgres.yhsjzabrlpgsgrpxaett
supabase.password=medflowbanco

spring.datasource.url=jdbc:postgresql://${supabase.url}:${supabase.port}/${supabase.db}
spring.datasource.username=${supabase.username}
spring.datasource.password=${supabase.password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.application.name=medflow-backend
server.port=8080

jwt.secret=medflow-super-secret-key-troque-isso-em-producao-123456789
jwt.expiration-ms=86400000

cors.allowed-origins=http://localhost:8080,http://localhost:3000,http://localhost:5500,http://127.0.0.1:5500,http://127.0.0.1:8080

# ================================================================
#  EMAIL SMTP (Gmail)
#  1. Ative verificacao em 2 etapas no Google
#  2. Gere uma Senha de App em: myaccount.google.com/apppasswords
#  3. Preencha abaixo
# ================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rodrigoconcei190@gmail.com
spring.mail.password=gcau vgxm zbwv itqp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Minutos de validade do codigo 2FA
twofa.expiry-minutes=5

logging.level.com.medframe=INFO
